In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn import neighbors, datasets
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler



n_neighbors = 5



# import some data to play with
epsomite = "https://rruff.info/repository/sample_child_record_raman/by_minerals/Epsomite__X050074__Raman__785__0__unoriented__Raman_Data_Processed__6540.txt"
scdat = np.recfromtxt(epsomite, names=['Raman_shift', 'intensity'])
intensity = scdat.intensity
#print(intensity)
raman = scdat.Raman_shift



calcite = "https://rruff.info/tmp_rruff/Calcite__R040070-3__Raman__514__0__depolarized__Raman_Data_Processed__11617.rruff"
scdat1 = np.recfromtxt(calcite, names=['Raman_shift', 'intensity'])
intensity1 = scdat1.intensity
#print(intensity)
raman1 = scdat1.Raman_shift



fluorite = "https://rruff.info/tmp_rruff/Fluorite__R050115-3__Raman__514__0__depolarized__Raman_Data_Processed__5427.rruff"
scdat2 = np.recfromtxt(fluorite, names=['Raman_shift', 'intensity'])
intensity2 = scdat2.intensity
#print(intensity)
raman2 = scdat2.Raman_shift



#a = np.array([[raman, raman1, raman2], [intensity, intensity1, intensity2]])
a = np.array([[raman, intensity], [raman1, intensity1], [raman2, intensity2]], dtype=object)
print(a)
    

X = a[:, :1]
y = a[1]
#print(X)
#print(y)


X = a[:, 1]
y = a[:, 1]


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)



classifier = KNeighborsClassifier(n_neighbors=5)
#classifier.fit(X_train, y_train)












[[array([b'206.000,', b'207.000,', b'208.000,', ..., b'1498.000,',
       b'1499.000,', b'1500.000,'], dtype='|S9')
  array([0.   , 0.095, 1.313, ..., 0.194, 0.35 , 0.   ])]
 [array([b'90.587,', b'91.981,', b'93.375,', ..., b'1519.113,',
       b'1520.288,', b'1521.463,'], dtype='|S9')
  array([ 0.   , 22.571,  0.16 , ...,  0.399, 61.312,  0.   ])]
 [array([b'97.628,', b'99.023,', b'100.418,', ..., b'1519.443,',
       b'1520.616,', b'1521.790,'], dtype='|S9')
  array([  0.   ,  39.119,  27.562, ..., 405.005,   0.987,   0.   ])]]


C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\npyio.py:2313: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  output = genfromtxt(fname, **kwargs)
